### ISSUE TITLE
Images in blog are loss

### ISSUE THREAD

**Issue by zhaokuohaha** [williamhallatt/aspnet-core-webapi-jwt-auth-example#1]
Hi , I'm learning use jwt in my webapi project. thanks for your blog and codes, they're helpful. 
but something was wrong, all of  the image are loss in the [blog](https://goblincoding.com/2016/07/03/issuing-and-authenticating-jwt-tokens-in-asp-net-core-webapi-part-i/) ,can you update blog ? 
Thank you !

**Comment by williamhallatt** [comment]
Hi there,

All the images work fine on my side, none are missing or restricted.

Kind regards,
William

**Comment by zhaokuohaha** [comment]
Oops, Sorry that.  
Perhaps because I'm in China.  I use vpn and it's find now !

btw: the blog is very helpful for me ~

**Comment by williamhallatt** [comment]
I'm very glad it is helping you. Have a great weekend!
